<?php
// ============================================================
// generate-report.php
// Generates an Admin System Summary PDF using FPDF
// ============================================================

// Load FPDF library (no composer needed)
require_once __DIR__ . '/../lib/fpdf/fpdf.php';

// ─── DATABASE CONNECTION ─────────────────────────────────────
require_once __DIR__ . '/db.php';

// ─── 1. SUMMARY DATA ─────────────────────────────────────────

// Total Passengers (boarding only)
$passResult = mysqli_query($conn, "
    SELECT COALESCE(SUM(quantity), 0) AS total
    FROM passenger_log
    WHERE action = 'Board'
");
$totalPassengers = (int) mysqli_fetch_assoc($passResult)['total'];

// Total Revenue
$revResult = mysqli_query($conn, "
    SELECT COALESCE(SUM(total_fare), 0) AS total
    FROM trip
");
$totalRevenue = (float) mysqli_fetch_assoc($revResult)['total'];

// Total Trips
$tripResult = mysqli_query($conn, "
    SELECT COUNT(*) AS total
    FROM trip
");
$totalTrips = (int) mysqli_fetch_assoc($tripResult)['total'];

// ─── 2. ROUTES DATA ──────────────────────────────────────────

$routesResult = mysqli_query($conn, "
    SELECT
        r.route_name,
        r.distance_km,
        COUNT(s.stop_id) AS stop_count
    FROM route r
    LEFT JOIN stop s ON r.route_id = s.route_id
    GROUP BY r.route_id, r.route_name, r.distance_km
    ORDER BY r.route_name ASC
");

$routes = [];
while ($row = mysqli_fetch_assoc($routesResult)) {
    $routes[] = $row;
}

// ─── 3. DRIVERS DATA ─────────────────────────────────────────

$driversResult = mysqli_query($conn, "
    SELECT full_name, status
    FROM driver
    ORDER BY full_name ASC
");

$drivers = [];
while ($row = mysqli_fetch_assoc($driversResult)) {
    $drivers[] = $row;
}

// ─── 4. VEHICLES DATA ────────────────────────────────────────

$vehiclesResult = mysqli_query($conn, "
    SELECT plate_number, vehicle_type, status
    FROM vehicle
    ORDER BY plate_number ASC
");

$vehicles = [];
while ($row = mysqli_fetch_assoc($vehiclesResult)) {
    $vehicles[] = $row;
}

mysqli_close($conn);

// ============================================================
// BUILD THE PDF
// ============================================================

// ─── CUSTOM FPDF CLASS (for header & footer) ─────────────────
class SmartSakayPDF extends FPDF
{
    // ── Page Header ──────────────────────────────────────────
    function Header()
    {
        // Dark header bar
        $this->SetFillColor(15, 23, 42);        // #0F172A
        $this->Rect(0, 0, 210, 28, 'F');

        // Title
        $this->SetFont('Arial', 'B', 16);
        $this->SetTextColor(255, 255, 255);
        $this->SetXY(0, 7);
        $this->Cell(210, 8, 'Smart Sakay Report', 0, 1, 'C');

        // Subtitle
        $this->SetFont('Arial', '', 9);
        $this->SetTextColor(148, 163, 184);     // slate-400
        $this->Cell(210, 6, 'Admin System Summary', 0, 1, 'C');

        // Accent line
        $this->SetFillColor(99, 102, 241);      // indigo-500
        $this->Rect(0, 28, 210, 1.5, 'F');

        // Date generated (right-aligned)
        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(100, 116, 139);
        $this->SetXY(0, 31);
        $this->Cell(205, 6, 'Generated: ' . date('F j, Y  g:i A'), 0, 0, 'R');

        $this->Ln(8);
    }

    // ── Page Footer ──────────────────────────────────────────
    function Footer()
    {
        $this->SetY(-14);

        // Footer line
        $this->SetFillColor(99, 102, 241);
        $this->Rect(0, $this->GetY(), 210, 0.5, 'F');

        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(100, 116, 139);
        $this->Cell(0, 10, 'Generated by Smart Sakay System', 0, 0, 'C');
    }

    // ── Section Heading ───────────────────────────────────────
    function SectionHeading($title)
    {
        $this->Ln(4);
        $this->SetFillColor(99, 102, 241);      // indigo accent
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial', 'B', 10);
        $this->Cell(0, 8, '  ' . strtoupper($title), 0, 1, 'L', true);
        $this->Ln(2);
    }

    // ── Table Header Row ─────────────────────────────────────
    function TableHeader($cols, $widths)
    {
        $this->SetFillColor(30, 41, 59);        // slate-800
        $this->SetTextColor(148, 163, 184);     // slate-400
        $this->SetFont('Arial', 'B', 8);
        foreach ($cols as $i => $col) {
            $this->Cell($widths[$i], 7, $col, 0, 0, 'L', true);
        }
        $this->Ln();
    }

    // ── Table Row ────────────────────────────────────────────
    function TableRow($cells, $widths, $fill = false)
    {
        if ($fill) {
            $this->SetFillColor(15, 23, 42);    // very dark row stripe
        } else {
            $this->SetFillColor(22, 33, 51);
        }
        $this->SetTextColor(226, 232, 240);     // slate-200
        $this->SetFont('Arial', '', 8.5);
        foreach ($cells as $i => $cell) {
            $this->Cell($widths[$i], 7, $cell, 0, 0, 'L', true);
        }
        $this->Ln();
    }

    // ── Status Badge ─────────────────────────────────────────
    function StatusCell($status, $width)
    {
        // Color-code status values
        if ($status === 'Active' || $status === 'Completed') {
            $this->SetTextColor(52, 211, 153);   // green
        } elseif ($status === 'Inactive' || $status === 'On Leave') {
            $this->SetTextColor(251, 146, 60);   // amber
        } else {
            $this->SetTextColor(226, 232, 240);
        }
        $this->SetFont('Arial', 'B', 8.5);
        $this->Cell($width, 7, $status, 0, 0, 'L', true);
        $this->SetTextColor(226, 232, 240);     // reset
        $this->SetFont('Arial', '', 8.5);
    }
}

// ─── INSTANTIATE PDF ─────────────────────────────────────────
$pdf = new SmartSakayPDF('P', 'mm', 'A4');
$pdf->SetAutoPageBreak(true, 20);
$pdf->SetMargins(15, 48, 15);
$pdf->AddPage();

// Dark page background
$pdf->SetFillColor(8, 15, 30);
$pdf->Rect(0, 29.5, 210, 268, 'F');

// ============================================================
// SECTION 1 — SUMMARY
// ============================================================
$pdf->SectionHeading('1. Summary');

// Summary cards (3 stats in one row)
$cardW   = 58;
$cardH   = 22;
$cardGap = 3;
$startX  = 15;
$startY  = $pdf->GetY();

$stats = [
    ['label' => 'Total Trips',      'value' => number_format($totalTrips),                   'icon' => 'Trips'],
    ['label' => 'Total Passengers', 'value' => number_format($totalPassengers),               'icon' => 'Pax'],
    ['label' => 'Total Revenue',    'value' => 'PHP ' . number_format($totalRevenue, 2), 'icon' => 'Rev'],
];

foreach ($stats as $i => $stat) {
    $x = $startX + $i * ($cardW + $cardGap);
    // Card background
    $pdf->SetFillColor(22, 33, 62);
    $pdf->Rect($x, $startY, $cardW, $cardH, 'F');

    // Indigo accent stripe on left
    $pdf->SetFillColor(99, 102, 241);
    $pdf->Rect($x, $startY, 2.5, $cardH, 'F');

    // Label
    $pdf->SetFont('Arial', '', 7.5);
    $pdf->SetTextColor(148, 163, 184);
    $pdf->SetXY($x + 5, $startY + 3);
    $pdf->Cell($cardW - 5, 5, $stat['label'], 0, 0);

    // Value
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->SetXY($x + 5, $startY + 10);
    $pdf->Cell($cardW - 5, 7, $stat['value'], 0, 0);
}

$pdf->SetY($startY + $cardH + 6);

// ============================================================
// SECTION 2 — ROUTES SUMMARY
// ============================================================
$pdf->SectionHeading('2. Routes Summary');

$colLabels = ['Route Name', 'Distance (km)', 'No. of Stops'];
$colWidths = [100, 50, 30];

$pdf->TableHeader($colLabels, $colWidths);

$fill = false;
foreach ($routes as $route) {
    // Auto page-break check
    if ($pdf->GetY() > 250) {
        $pdf->AddPage();
        $pdf->TableHeader($colLabels, $colWidths);
    }

    $pdf->SetFillColor($fill ? 15 : 22, $fill ? 23 : 33, $fill ? 42 : 51);
    $pdf->SetTextColor(226, 232, 240);
    $pdf->SetFont('Arial', '', 8.5);
    $pdf->Cell($colWidths[0], 7, $route['route_name'], 0, 0, 'L', true);
    $pdf->Cell($colWidths[1], 7, number_format((float)$route['distance_km'], 2) . ' km', 0, 0, 'L', true);
    $pdf->Cell($colWidths[2], 7, $route['stop_count'], 0, 1, 'L', true);

    $fill = !$fill;
}

$pdf->Ln(2);

// ============================================================
// SECTION 3 — DRIVERS SUMMARY
// ============================================================
$pdf->SectionHeading('3. Drivers Summary');

$driverCols   = ['Driver Name', 'Status'];
$driverWidths = [150, 30]; // 180 total

$pdf->TableHeader($driverCols, $driverWidths);

$fill = false;
foreach ($drivers as $driver) {
    if ($pdf->GetY() > 250) {
        $pdf->AddPage();
        $pdf->TableHeader($driverCols, $driverWidths);
    }

    $pdf->SetFillColor($fill ? 15 : 22, $fill ? 23 : 33, $fill ? 42 : 51);
    $pdf->SetFont('Arial', '', 8.5);
    $pdf->SetTextColor(226, 232, 240);
    $pdf->Cell($driverWidths[0], 7, $driver['full_name'], 0, 0, 'L', true);
    $pdf->StatusCell($driver['status'], $driverWidths[1]);
    $pdf->Ln();

    $fill = !$fill;
}

$pdf->Ln(2);

// ============================================================
// SECTION 4 — VEHICLES SUMMARY
// ============================================================
$pdf->SectionHeading('4. Vehicles Summary');

$vehCols   = ['Plate Number', 'Vehicle Type', 'Status'];
$vehWidths = [55, 100, 25]; // 180 total

$pdf->TableHeader($vehCols, $vehWidths);

$fill = false;
foreach ($vehicles as $vehicle) {
    if ($pdf->GetY() > 250) {
        $pdf->AddPage();
        $pdf->TableHeader($vehCols, $vehWidths);
    }

    $pdf->SetFillColor($fill ? 15 : 22, $fill ? 23 : 33, $fill ? 42 : 51);
    $pdf->SetFont('Arial', '', 8.5);
    $pdf->SetTextColor(226, 232, 240);
    $pdf->Cell($vehWidths[0], 7, $vehicle['plate_number'], 0, 0, 'L', true);
    $pdf->Cell($vehWidths[1], 7, $vehicle['vehicle_type'], 0, 0, 'L', true);
    $pdf->StatusCell($vehicle['status'], $vehWidths[2]);
    $pdf->Ln();

    $fill = !$fill;
}

// ─── OUTPUT PDF ──────────────────────────────────────────────
// 'D' = force download, 'I' = open in browser
$pdf->Output('D', 'SmartSakay_Admin_Report_' . date('Y-m-d') . '.pdf');
?>
